version: '3'

volumes:
  managed_docu_familiarization_local_postgres_data: {}
  managed_docu_familiarization_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: managed_docu_familiarization_local_django
    container_name: managed_docu_familiarization_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: managed_docu_familiarization_production_postgres
    container_name: managed_docu_familiarization_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - managed_docu_familiarization_local_postgres_data:/var/lib/postgresql/data
      - managed_docu_familiarization_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: managed_docu_familiarization_local_docs
    container_name: managed_docu_familiarization_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./managed_docu_familiarization:/app/managed_docu_familiarization:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: managed_docu_familiarization_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: managed_docu_familiarization_redis