# Generated by Django 4.1.9 on 2024-08-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HRPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name of the person",
                        max_length=40,
                        null=True,
                        verbose_name="First name",
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        blank=True,
                        help_text="Family name of the person",
                        max_length=40,
                        null=True,
                        verbose_name="Family name",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Person",
                "verbose_name_plural": "HR People",
                "ordering": ["family_name"],
            },
        ),
    ]
