#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

>&1 echo 'Collecting static files'
python /app/manage.py collectstatic --noinput

>&1 echo 'Doing migrations with normal account - if this does not work, temporarily elevate rights for the DB user'
python /app/manage.py migrate

# start the periodic tasks, the & symbol sends the execution to background
# (so the script continues to start the server)
>&1 echo 'Starting Celery periodic tasks'
celery -A managed_docu_familiarization worker -l info --concurrency 1 &
celery -A managed_docu_familiarization beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler &

>&1 echo 'Starting the server'
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --timeout 600
