# Generated by Django 4.1.9 on 2024-11-02 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                ("doc_name", models.CharField(max_length=255)),
                ("doc_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Private documents"),
                            (2, "Public documents"),
                            (3, "Documents for certain groups"),
                        ],
                        verbose_name="Category",
                    ),
                ),
                ("release_date", models.DateField()),
                (
                    "groups",
                    models.ManyToManyField(related_name="documents", to="auth.group"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentAgreement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="mdf.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "document")},
            },
        ),
    ]
