# Generated by Django 4.1.9 on 2024-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="release_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
