# Generated by Django 4.1.9 on 2024-11-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mdf", "0002_alter_document_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="documents", to="auth.group"
            ),
        ),
    ]
