# Generated by Django 4.1.9 on 2024-11-08 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdf", "0004_alter_document_doc_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentagreement",
            options={"verbose_name": "Consent", "verbose_name_plural": "Consents"},
        ),
        migrations.AlterUniqueTogether(
            name="documentagreement",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="document",
            name="contact_users",
            field=models.ManyToManyField(
                related_name="document_contact_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
