# Generated by Django 4.1.9 on 2024-11-11 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdf", "0005_alter_documentagreement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentagreement",
            options={},
        ),
        migrations.AddField(
            model_name="document",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="documentagreement",
            unique_together={("user", "document")},
        ),
    ]
