# Generated by Django 4.1.9 on 2024-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mdf", "0006_alter_documentagreement_options_document_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("processed", "Processed")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="document_groups", to="auth.group"
            ),
        ),
    ]
