# Generated by Django 4.1.9 on 2024-12-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0007_document_status_alter_document_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentagreement",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentagreement",
            name="reading_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
