# Generated by Django 4.1.9 on 2024-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0008_documentagreement_open_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                ],
                default="uploaded",
                max_length=10,
            ),
        ),
    ]
