# Generated by Django 4.1.9 on 2024-12-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdf", "0009_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="responsible_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="document_responsible_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
