# Generated by Django 4.1.9 on 2025-01-07 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdf", "0010_document_responsible_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="contact_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="document_contact_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("expired", "Expired"),
                ],
                default="uploaded",
                max_length=10,
            ),
        ),
    ]
