# Generated by Django 4.1.9 on 2025-02-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0011_alter_document_contact_users_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_ver",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="document",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mdf.document",
            ),
        ),
    ]
