# Generated by Django 4.1.9 on 2025-03-09 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdf", "0012_document_doc_ver_document_previous_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="approved_by_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="document_users_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="doc_category",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Standard"),
                    (2, "Guideline"),
                    (3, "Workflows"),
                    (4, "Manual"),
                ],
                null=True,
                verbose_name="Document category",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("waiting_owner", "Waiting"),
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("expired", "Expired"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
