# Generated by Django 4.1.9 on 2025-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0013_document_approved_by_users_document_doc_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Private documents"),
                    (2, "Public documents"),
                    (3, "Documents for certain groups"),
                ],
                default=1,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_ver",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("waiting_owner", "Waiting for owner"),
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("expired", "Expired"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
