# Generated by Django 4.1.9 on 2025-03-31 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mdf", "0014_alter_document_category_alter_document_doc_ver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentagreement",
            name="open_count",
        ),
    ]
